server:
  port: 8080
spring:
  application:
    name: blog-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 2000
        log4j:
          enabled: true
      stat-view-servlet:
        login-username: qingchun
        login-password: 729512117
        enabled: true
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,.gif,.jpg,.css,/druid/*
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      url: jdbc:mysql://localhost:3306/blog?Encoding=utf-8&useSSL=false&ServerTimezone=GMT%2B8
      username: root
      password: 729512117
      driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: zhuqingchun
    password: 729512117
  redis:
    cluster:
      nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
      max-redirects: 2
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        max-active: 8
  elasticsearch:
    rest:
      uris: http://localhost:9201
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.user.entity

#jwt configuration
jwt:
  tokenHeader: accessToken
  authHeader: authorities
  tokenPrefix: Bearer
  secret: sexygirls
  expiration: 60